/**
 * Phase 1 — Archon DAG loader with Hephaestus back-compat shim.
 *
 * Dispatches between two on-disk shapes per workflow directory:
 *
 *   1. Single-file DAG workflow — `workflows/<name>/workflow.yaml` has a
 *      top-level `nodes:` array. Validated against `workflowDefinitionSchema`
 *      (the ported Archon shape) and returned as a `DagWorkflowWithSource`.
 *
 *   2. Hephaestus split workflow — `workflows/<name>/workflow.yaml` has
 *      `phase_order:` but NO `nodes:`, plus a `phases/NN_<id>.yaml` file per
 *      phase. Loaded via the EXISTING `validateWorkflowConfig` / `validatePhase`
 *      from `./types.ts`, then adapted into a synthetic `WorkflowDefinition`
 *      whose nodes are a linear chain of `prompt:` nodes (one per phase, each
 *      depending on the previous). This preserves the 5 existing Hephaestus
 *      workflows (`bug-fix`, `doc-gen`, `feature-dev`, `index-repo`,
 *      `prd-to-software`) unchanged on disk while letting the new executor
 *      (Phase 2) treat them uniformly.
 *
 * Secret-pattern reject (per plan Phase 1 + acceptance gate): for every
 * `bash:` or `script:` body in a DAG workflow, scan for `$<NAME>_API_KEY`,
 * `$<NAME>_SECRET`, `$<NAME>_TOKEN` references and reject at load time so
 * authors can't accidentally smuggle secrets through `process.env` expansion.
 * Allowlist of env names that bash/script nodes can reference is in the
 * executor's `env-sanitizer.ts` (Phase 2); the load-time check is a
 * defense-in-depth complement.
 */

import * as fs from 'fs';
import * as path from 'path';

import jsYaml from 'js-yaml';
import { z } from 'zod';

import { getRegisteredGroup } from '../db.js';
import { logger } from '../logger.js';
// Phase 1.7 — bundled defaults codegen output. Generated by
// `scripts/build-bundled-workflows.ts` via the `prebuild` script. Gitignored.
// If you see "Cannot find module './bundled-defaults.generated.js'", run
// `npm run prebuild`.
import { BUNDLED_WORKFLOW_YAML as bundledYamlMap } from './bundled-defaults.generated.js';

import {
  workflowDefinitionSchema,
  type DagNode,
  type WorkflowDefinition,
  type WorkflowLoadError,
  type WorkflowSource,
  type WorkflowWithSource,
} from './schemas/index.js';
import {
  validatePhase,
  validateWorkflowConfig,
  WorkflowSchemaError,
  type Phase,
  type Workflow,
} from './types.js';

// ─── public types ───────────────────────────────────────────────────────────

/**
 * Pair (workflow, source) — `project` for filesystem-loaded, `hephaestus` for
 * shimmed split-layout workflows, `bundled` for codegen output (Phase 1.7).
 */
export interface DagWorkflowWithSource extends WorkflowWithSource {
  readonly workflow: WorkflowDefinition;
  readonly source: WorkflowSource;
}

/** Result of `loadAllDagWorkflows()` — pairs map + parallel error list. */
export interface DagWorkflowLoadResult {
  readonly workflows: Map<string, DagWorkflowWithSource>;
  readonly errors: readonly WorkflowLoadError[];
}

// ─── Phase 2 — remote fetch cache (workspaceId × workflowName) ─────────────
//
// Separate from the on-disk `_dagCache`. Each entry holds the last parsed
// workflow, the etag used for the If-None-Match handshake, and the timestamp
// of the last successful response (200 or 304) so the 60 s TTL can be
// evaluated without hitting the network.
//
// IMPORTANT: `ARCHON_DAG_REMOTE_FETCH_ENABLED=1` must be set in the droplet
// .env to activate the HTTP fetch path. Default is `0` (off); flipped to `1`
// in Phase 4 after smoke validation confirms the endpoint is stable.

interface RemoteFetchCacheEntry {
  etag: string;
  workflow: WorkflowDefinition;
  fetchedAt: number;
}

/** Key: `${workspaceId}::${workflowName}` */
const _remoteCache = new Map<string, RemoteFetchCacheEntry>();

/** 60 s TTL for remote-fetched workflows. */
const REMOTE_CACHE_TTL_MS = 60_000;

/** Test-only: clear the remote fetch cache between tests. */
export function _resetRemoteFetchCache(): void {
  _remoteCache.clear();
}

// ─── module-level cache (separate from legacy loader's cache) ──────────────

let _dagCache: DagWorkflowLoadResult | null = null;

/** Directory containing all workflows. Override via `WORKFLOWS_DIR` env var.
 *  Resolved lazily so test setups that mutate `process.env` after import still
 *  take effect. */
function workflowsDir(): string {
  return process.env.WORKFLOWS_DIR || path.resolve(process.cwd(), 'workflows');
}

/**
 * Load every workflow under `WORKFLOWS_DIR`, dispatching between Hephaestus
 * split layout (back-compat) and DAG single-file layout.
 *
 * Failures on individual workflows are collected into `errors` rather than
 * thrown, so a single broken workflow doesn't take down the whole registry.
 * Callers that want strict load-or-die semantics should check
 * `result.errors.length === 0` and refuse to proceed.
 */
export function loadAllDagWorkflows(): DagWorkflowLoadResult {
  if (_dagCache) return _dagCache;
  _dagCache = doLoad(workflowsDir());
  return _dagCache;
}

/** Look up a single workflow by directory name. Triggers initial load if needed. */
export function loadDagWorkflow(name: string): DagWorkflowWithSource | null {
  const { workflows } = loadAllDagWorkflows();
  return workflows.get(name) ?? null;
}

/** Re-run the loader, replacing the cache. Used by `POST /workflows/reload`. */
export function reloadDagWorkflows(): DagWorkflowLoadResult {
  const fresh = doLoad(workflowsDir());
  _dagCache = fresh;
  const names = Array.from(fresh.workflows.keys()).sort();
  logger.info(
    { count: fresh.workflows.size, errorCount: fresh.errors.length, names },
    'dag workflows reloaded',
  );
  return fresh;
}

/** Test-only: blow away the cache so tests can re-load fixture dirs. */
export function _resetDagWorkflowCache(): void {
  _dagCache = null;
}

/** Test-only: load from an arbitrary directory. */
export function _loadDagFromDir(dir: string): DagWorkflowLoadResult {
  return doLoad(dir);
}

/**
 * Phase 2 — workspace-scoped DAG workflow loader with remote fetch + disk
 * fallback. Used by the ConcurrencyScanner (src/index.ts) when a workflow run
 * has a `chat_jid` that can be resolved to a `workspaceId`.
 *
 * Algorithm:
 *   1. Resolve `chatJid` → `workspaceId` via the registered_groups table
 *      (or via `_resolveWorkspaceId` for tests — dependency injection).
 *      If unresolvable, log a warning and fall back to disk-only.
 *   2. Check the in-memory cache for `(workspaceId, name)`. If `fetchedAt`
 *      is within the 60 s TTL, return the cached entry immediately.
 *   3. Fire a GET to `${DELEGATE_API_BASE}/api/agent/workflows/dag/:name`
 *      with an `If-None-Match` header when a cached etag exists.
 *      5 s timeout via `AbortSignal.timeout(5000)`.
 *   4. Branch on status:
 *      - 200 → parse envelope, extract `body.workflow`, validate with
 *              `workflowDefinitionSchema`, overwrite cache.
 *      - 304 → refresh `fetchedAt` only (cheap revalidation).
 *      - 404 / 5XX / throw → warn + fall back to disk.
 *
 * GATED by `ARCHON_DAG_REMOTE_FETCH_ENABLED=1`. When the flag is absent or
 * `0`, the function skips the HTTP fetch and returns the disk result directly.
 * This is the safe default for production until Phase 4 validation.
 *
 * Disk fallback (`loadDagWorkflow(name)`) is always the last resort so DA
 * degrades gracefully when the Delegate API is unreachable.
 *
 * @param _resolveWorkspaceId — optional override for tests; production uses
 *   `getRegisteredGroup(chatJid)?.workspaceId` from the group store.
 */
export async function loadDagWorkflowForGroup(
  name: string,
  chatJid: string | undefined,
  _resolveWorkspaceId?: (jid: string) => string | undefined,
): Promise<DagWorkflowWithSource | null> {
  // ── Flag gate ──────────────────────────────────────────────────────────
  const flagEnabled = process.env.ARCHON_DAG_REMOTE_FETCH_ENABLED === '1';
  if (!flagEnabled) {
    return loadDagWorkflow(name);
  }

  // ── Resolve workspaceId from chatJid ───────────────────────────────────
  let workspaceId: string | undefined;
  if (chatJid) {
    if (_resolveWorkspaceId) {
      workspaceId = _resolveWorkspaceId(chatJid);
    } else {
      const group = getRegisteredGroup(chatJid);
      workspaceId = group?.workspaceId;
    }
  }

  if (!workspaceId) {
    logger.warn(
      { name, chatJid },
      'dag.remote.fetch.no_workspace — falling back to disk',
    );
    return loadDagWorkflow(name);
  }

  const cacheKey = `${workspaceId}::${name}`;
  const cached = _remoteCache.get(cacheKey);

  // ── Cache hit within TTL ───────────────────────────────────────────────
  if (cached && Date.now() - cached.fetchedAt < REMOTE_CACHE_TTL_MS) {
    return { workflow: cached.workflow, source: 'remote' as WorkflowSource };
  }

  // ── HTTP fetch ─────────────────────────────────────────────────────────
  const baseUrl = process.env.DELEGATE_API_BASE ?? 'https://delegate.ws';
  const token = process.env.DELEGATE_AGENT_TOKEN ?? '';
  const url = `${baseUrl}/api/agent/workflows/dag/${encodeURIComponent(name)}?workspaceId=${encodeURIComponent(workspaceId)}`;

  const headers: Record<string, string> = {
    Authorization: `Bearer ${token}`,
    Accept: 'application/json',
  };
  if (cached?.etag) {
    headers['If-None-Match'] = cached.etag;
  }

  let res: Response;
  try {
    res = await fetch(url, {
      headers,
      signal: AbortSignal.timeout(5000),
    });
  } catch (err) {
    logger.warn(
      { name, workspaceId, err },
      'dag.remote.fetch.network_error — falling back to disk',
    );
    return loadDagWorkflow(name);
  }

  // ── 304 — cheap revalidation ───────────────────────────────────────────
  if (res.status === 304) {
    if (cached) {
      _remoteCache.set(cacheKey, { ...cached, fetchedAt: Date.now() });
      return { workflow: cached.workflow, source: 'remote' as WorkflowSource };
    }
    // 304 without a cached entry: fall back to disk (shouldn't happen in
    // practice since we only send If-None-Match when cached is present).
    logger.warn(
      { name, workspaceId },
      'dag.remote.fetch.304_without_cache — falling back to disk',
    );
    return loadDagWorkflow(name);
  }

  // ── 200 — full response ────────────────────────────────────────────────
  if (res.status === 200) {
    let body: unknown;
    try {
      body = await res.json();
    } catch (err) {
      logger.warn(
        { name, workspaceId, err },
        'dag.remote.fetch.invalid_json — falling back to disk',
      );
      return loadDagWorkflow(name);
    }

    // Unwrap the apiSuccess envelope: body = { data: { name, kind, workflow,
    // source, etag }, success: true }. Accept both wrapped and unwrapped for
    // resilience.
    const envelope =
      body !== null &&
      typeof body === 'object' &&
      'data' in (body as Record<string, unknown>)
        ? (body as { data: unknown }).data
        : body;

    if (
      envelope === null ||
      typeof envelope !== 'object' ||
      !('workflow' in (envelope as Record<string, unknown>))
    ) {
      logger.warn(
        { name, workspaceId, envelope },
        'dag.remote.fetch.malformed_envelope — falling back to disk',
      );
      return loadDagWorkflow(name);
    }

    const envelopeObj = envelope as Record<string, unknown>;

    // C5 fix: extract body.workflow (the inner definition), NOT the whole
    // envelope. `workflowDefinitionSchema` validates only the inner object.
    const rawWorkflow = envelopeObj.workflow;

    const parsed = workflowDefinitionSchema.safeParse(rawWorkflow);
    if (!parsed.success) {
      logger.warn(
        { name, workspaceId, error: parsed.error.message },
        'dag.remote.fetch.schema_invalid — falling back to disk',
      );
      return loadDagWorkflow(name);
    }

    // Etag precedence (RFC 9110): HTTP header wins over body.etag when both
    // are present. Header is the canonical transport; body.etag is the
    // defense-in-depth fallback for clients behind proxies that strip headers.
    const etagFromHeader = res.headers.get('etag');
    const etagFromBody =
      typeof envelopeObj.etag === 'string' ? envelopeObj.etag : undefined;
    const etag = etagFromHeader ?? etagFromBody ?? `"v0"`;

    _remoteCache.set(cacheKey, {
      etag,
      workflow: parsed.data,
      fetchedAt: Date.now(),
    });

    logger.info(
      { name, workspaceId, etag, source: envelopeObj.source ?? 'override' },
      'dag.remote.fetch.ok',
    );

    return { workflow: parsed.data, source: 'remote' as WorkflowSource };
  }

  // ── 404 / 5XX / unexpected status ─────────────────────────────────────
  logger.warn(
    { name, workspaceId, status: res.status },
    'dag.remote.fetch.non_200 — falling back to disk',
  );
  return loadDagWorkflow(name);
}

// ─── internals ──────────────────────────────────────────────────────────────

function doLoad(rootDir: string): DagWorkflowLoadResult {
  const workflows = new Map<string, DagWorkflowWithSource>();
  const errors: WorkflowLoadError[] = [];

  if (fs.existsSync(rootDir)) {
    let entries: fs.Dirent[];
    try {
      entries = fs.readdirSync(rootDir, { withFileTypes: true });
    } catch (err) {
      logger.error({ err, rootDir }, 'failed to read workflows directory');
      entries = [];
    }

    for (const ent of entries) {
      if (!ent.isDirectory()) continue;
      const name = ent.name;
      const dir = path.join(rootDir, name);
      try {
        const loaded = loadOne(name, dir);
        workflows.set(name, loaded);
      } catch (err) {
        const message = err instanceof Error ? err.message : String(err);
        const errorType =
          err instanceof WorkflowSchemaError || err instanceof z.ZodError
            ? 'validation_error'
            : 'parse_error';
        errors.push({
          filename: path.join(name, 'workflow.yaml'),
          error: message,
          errorType,
        });
        logger.error({ err, name }, 'workflow load failed');
      }
    }
  } else {
    logger.warn(
      { rootDir },
      'workflows directory does not exist — falling back to bundled defaults only',
    );
  }

  // Phase 1.7 — layer in bundled defaults for any workflow name not already
  // resolved from the filesystem. Precedence: project > bundled (per plan).
  loadBundledDefaults(workflows, errors);

  return { workflows, errors };
}

/**
 * Phase 1.7 — load every bundled workflow whose name is NOT already in the
 * map. The codegen output (`bundled-defaults.generated.ts`) re-validated each
 * YAML at build time, but we re-validate at load time too: belt-and-braces
 * against a hand-edited generated file slipping in, AND uniform error
 * handling with project loads.
 *
 * Best-effort: a broken bundled workflow lands in `errors` rather than
 * throwing, matching the project-load behavior.
 */
function loadBundledDefaults(
  workflows: Map<string, DagWorkflowWithSource>,
  errors: WorkflowLoadError[],
): void {
  let bundled: Readonly<Record<string, string>>;
  try {
    // Lazy import — keeps the bundle out of test contexts that don't need it
    // and gracefully handles the gitignored file being absent (tests that
    // run before `npm run prebuild`).
    bundled = bundledWorkflowYamlOrEmpty();
  } catch (err) {
    logger.warn(
      { err },
      'bundled defaults unavailable — skipping (run `npm run prebuild`?)',
    );
    return;
  }

  for (const [name, yamlText] of Object.entries(bundled)) {
    if (workflows.has(name)) continue; // project takes precedence
    try {
      const raw = jsYaml.load(yamlText);
      if (typeof raw !== 'object' || raw === null || Array.isArray(raw)) {
        throw new WorkflowSchemaError(
          `bundled:${name}`,
          '<root>',
          'workflow.yaml must be a YAML mapping',
        );
      }
      const wf = validateDagWorkflow(raw, `bundled:${name}`);
      workflows.set(name, { workflow: wf, source: 'bundled' });
    } catch (err) {
      const message = err instanceof Error ? err.message : String(err);
      const errorType =
        err instanceof WorkflowSchemaError || err instanceof z.ZodError
          ? 'validation_error'
          : 'parse_error';
      errors.push({
        filename: `bundled:${name}`,
        error: message,
        errorType,
      });
      logger.error({ err, name }, 'bundled workflow load failed');
    }
  }
}

// Read the codegen output. Static import means the generated file MUST exist
// at module-load time. `npm run prebuild` (wired into `npm run build` and
// `npm test` as hooks) regenerates it from workflows/archon-* / workflow.yaml.
// Fresh clones must run `npm install && npm run prebuild` before agent boot.
function bundledWorkflowYamlOrEmpty(): Readonly<Record<string, string>> {
  return bundledYamlMap;
}

function loadOne(name: string, dir: string): DagWorkflowWithSource {
  const cfgFile = path.join(dir, 'workflow.yaml');
  if (!fs.existsSync(cfgFile)) {
    throw new WorkflowSchemaError(
      relPath(cfgFile),
      '<file>',
      'missing workflow.yaml',
    );
  }

  const raw = readYaml(cfgFile);
  if (typeof raw !== 'object' || raw === null || Array.isArray(raw)) {
    throw new WorkflowSchemaError(
      relPath(cfgFile),
      '<root>',
      'workflow.yaml must be a YAML mapping',
    );
  }
  const obj = raw as Record<string, unknown>;

  // Dispatch: single-file DAG if top-level `nodes:` exists; else Hephaestus
  // split-layout back-compat shim.
  if (Array.isArray(obj.nodes)) {
    const wf = validateDagWorkflow(obj, cfgFile);
    return { workflow: wf, source: 'project' };
  }

  if (Array.isArray(obj.phase_order)) {
    const phasesDir = path.join(dir, 'phases');
    if (!fs.existsSync(phasesDir)) {
      throw new WorkflowSchemaError(
        relPath(phasesDir),
        '<dir>',
        'missing phases/ directory (Hephaestus split-layout workflow)',
      );
    }
    const hephaestus = loadHephaestusSplit(name, dir, cfgFile, raw);
    const wf = adaptHephaestusToDag(hephaestus);
    return { workflow: wf, source: 'hephaestus' };
  }

  throw new WorkflowSchemaError(
    relPath(cfgFile),
    '<root>',
    "workflow.yaml must have either 'nodes:' (DAG) or 'phase_order:' (Hephaestus split layout)",
  );
}

/** DAG single-file: validate against `workflowDefinitionSchema`, then run
 *  secret-pattern pre-flight on bash/script bodies. */
function validateDagWorkflow(raw: unknown, file: string): WorkflowDefinition {
  const parsed = workflowDefinitionSchema.safeParse(raw);
  if (!parsed.success) {
    throw new WorkflowSchemaError(
      relPath(file),
      parsed.error.issues[0]?.path.join('.') || '<root>',
      formatZodIssues(parsed.error),
    );
  }
  const wf = parsed.data;
  enforceUniqueNodeIds(wf.nodes, file);
  enforceDependencyClosure(wf.nodes, file);
  for (const node of wf.nodes) {
    enforceSecretLeakReject(node, file);
  }
  return wf;
}

/** Read + validate a Hephaestus split-layout workflow using the existing
 *  legacy validators. Does NOT pass through Zod. */
function loadHephaestusSplit(
  _name: string,
  dir: string,
  cfgFile: string,
  cfgRaw: unknown,
): Workflow {
  const phasesDir = path.join(dir, 'phases');
  const config = validateWorkflowConfig(cfgRaw, relPath(cfgFile));

  // Parse phase files in numeric filename order.
  const phaseEntries = fs
    .readdirSync(phasesDir, { withFileTypes: true })
    .filter((e) => e.isFile() && /\.ya?ml$/i.test(e.name))
    .map((e) => e.name)
    .sort();

  const phasesById = new Map<string, Phase>();
  for (const fname of phaseEntries) {
    const fpath = path.join(phasesDir, fname);
    const raw = readYaml(fpath);
    const phase = validatePhase(raw, relPath(fpath));
    if (phasesById.has(phase.id)) {
      throw new WorkflowSchemaError(
        relPath(fpath),
        'id',
        `duplicate phase id "${phase.id}" — already declared in another file`,
      );
    }
    phasesById.set(phase.id, phase);
  }

  // Reconcile config.phase_order against actual phase files.
  const orderedPhases: Phase[] = [];
  for (let i = 0; i < config.phase_order.length; i++) {
    const id = config.phase_order[i];
    const p = phasesById.get(id);
    if (!p) {
      throw new WorkflowSchemaError(
        relPath(cfgFile),
        `phase_order[${i}]`,
        `references phase "${id}" but no matching phase file found in ${relPath(phasesDir)}`,
      );
    }
    orderedPhases.push(p);
  }
  for (const id of phasesById.keys()) {
    if (!config.phase_order.includes(id)) {
      throw new WorkflowSchemaError(
        relPath(cfgFile),
        'phase_order',
        `phase "${id}" exists as a file but is not listed in phase_order`,
      );
    }
  }

  return { config, phases: orderedPhases };
}

/**
 * Adapt a Hephaestus `Workflow` into a synthetic `WorkflowDefinition` for the
 * new executor. Each phase becomes a `prompt:` node whose body is the phase's
 * `description` + `done_definitions` + `additional_notes` rendered as a
 * single template, and which depends on the previous phase's node.
 *
 * Loop signal mapping: when the executor (Phase 2+) sees a prompt node
 * adapted from a Hephaestus phase, it propagates the legacy
 * `phase_complete:<id>` signal as the node's completion gate. v1 schemas
 * preserve the description verbatim so existing phase-block injection logic
 * in `app/api/agent/channel/poll/route.ts` keeps working when the legacy
 * path is selected (per AC A10).
 */
function adaptHephaestusToDag(hephaestus: Workflow): WorkflowDefinition {
  const nodes: DagNode[] = hephaestus.phases.map((phase, i) => {
    const dependsOn = i === 0 ? undefined : [hephaestus.phases[i - 1].id];
    const promptBody = renderHephaestusPhasePrompt(phase);
    return {
      id: phase.id,
      ...(dependsOn ? { depends_on: dependsOn } : {}),
      prompt: promptBody,
    } as DagNode;
  });

  return {
    name: hephaestus.config.name,
    description: hephaestus.config.description,
    nodes,
    // Hephaestus tagging: surface result fields as workflow tags so callers
    // can detect "this came from the split-layout shim" without sniffing the
    // node shape. v1 executor uses workflow.tags for nothing else.
    tags: ['hephaestus', `has_result:${hephaestus.config.has_result}`],
  } satisfies WorkflowDefinition;
}

function renderHephaestusPhasePrompt(phase: Phase): string {
  const sections: string[] = [];
  sections.push(`# ${phase.name}`);
  if (phase.description.trim().length > 0) sections.push(phase.description);
  if (phase.done_definitions.length > 0) {
    sections.push('## Definition of done');
    sections.push(phase.done_definitions.map((d) => `- ${d}`).join('\n'));
  }
  if (phase.additional_notes.trim().length > 0) {
    sections.push('## Notes');
    sections.push(phase.additional_notes);
  }
  if (phase.outputs.length > 0) {
    sections.push('## Outputs');
    sections.push(phase.outputs.map((d) => `- ${d}`).join('\n'));
  }
  if (phase.next_steps.length > 0) {
    sections.push('## Next steps');
    sections.push(phase.next_steps.map((d) => `- ${d}`).join('\n'));
  }
  return sections.join('\n\n');
}

// ─── validation helpers ────────────────────────────────────────────────────

function enforceUniqueNodeIds(nodes: readonly DagNode[], file: string): void {
  const seen = new Set<string>();
  for (let i = 0; i < nodes.length; i++) {
    const id = nodes[i].id;
    if (seen.has(id)) {
      throw new WorkflowSchemaError(
        relPath(file),
        `nodes[${i}].id`,
        `duplicate node id "${id}"`,
      );
    }
    seen.add(id);
  }
}

function enforceDependencyClosure(
  nodes: readonly DagNode[],
  file: string,
): void {
  const ids = new Set(nodes.map((n) => n.id));
  for (let i = 0; i < nodes.length; i++) {
    const n = nodes[i];
    if (!n.depends_on) continue;
    for (let j = 0; j < n.depends_on.length; j++) {
      const ref = n.depends_on[j];
      if (!ids.has(ref)) {
        throw new WorkflowSchemaError(
          relPath(file),
          `nodes[${i}].depends_on[${j}]`,
          `references unknown node id "${ref}"`,
        );
      }
    }
  }
}

/**
 * Reject `bash:` and `script:` bodies that literally reference env names
 * matching `_API_KEY` / `_SECRET` / `_TOKEN` (the OneCLI-injected secret
 * pattern). This is a defense-in-depth check at LOAD time; the executor
 * (Phase 2's `env-sanitizer.ts`) is the runtime gate.
 *
 * Plain `$NAME` and `${NAME}` forms are both detected. The check is
 * case-sensitive — OneCLI env names are uppercase by convention.
 */
function enforceSecretLeakReject(node: DagNode, file: string): void {
  const body = nodeShellBody(node);
  if (body === null) return;

  const SECRET_PATTERN =
    /\$\{?[A-Z][A-Z0-9_]*(?:_API_KEY|_SECRET|_TOKEN|_PASSWORD)\}?/g;
  const matches = body.match(SECRET_PATTERN);
  if (matches && matches.length > 0) {
    const sample = matches[0];
    throw new WorkflowSchemaError(
      relPath(file),
      `nodes[${node.id}]`,
      `bash/script body references disallowed env name '${sample}' — secrets flow via OneCLI at request time, never via shell expansion`,
    );
  }
}

function nodeShellBody(node: DagNode): string | null {
  if ('bash' in node && typeof node.bash === 'string') return node.bash;
  if ('script' in node && typeof node.script === 'string') return node.script;
  return null;
}

function formatZodIssues(err: z.ZodError): string {
  return err.issues
    .map((iss) => {
      const p = iss.path.length > 0 ? iss.path.join('.') : '<root>';
      return `${p}: ${iss.message}`;
    })
    .join('; ');
}

function readYaml(file: string): unknown {
  let text: string;
  try {
    text = fs.readFileSync(file, 'utf-8');
  } catch (err) {
    throw new WorkflowSchemaError(
      relPath(file),
      '<file>',
      `cannot read file: ${(err as Error).message}`,
    );
  }
  try {
    return jsYaml.load(text);
  } catch (err) {
    throw new WorkflowSchemaError(
      relPath(file),
      '<yaml>',
      `malformed YAML: ${(err as Error).message}`,
    );
  }
}

function relPath(p: string): string {
  const rel = path.relative(process.cwd(), p);
  if (!rel.startsWith('..') && !path.isAbsolute(rel)) return rel;
  return p;
}
